# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

ci:
  autofix_commit_msg: Apply automatic fixes from pre-commit hooks
  autofix_prs: true
  autoupdate_commit_msg: 'ci: Bump pre-commit hooks'
  autoupdate_schedule: quarterly

default_install_hook_types: [pre-commit, commit-msg]
default_stages: [pre-commit]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
        exclude: &whitespace_excludes '.*\.(md|map|bin)$'
      - id: end-of-file-fixer
        exclude: *whitespace_excludes
      - id: check-executables-have-shebangs
      - id: mixed-line-ending
        args: ['-f=lf']

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.2
    hooks:
      - id: ruff-check
        args: [--fix, --exit-non-zero-on-fix]
      - id: ruff-format

  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.1
    hooks:
      - id: codespell
        additional_dependencies:
          - tomli

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.15.0'
    hooks:
    -   id: mypy
        additional_dependencies:
          - 'types-PyYAML'

  - repo: https://github.com/espressif/conventional-precommit-linter
    rev: v1.10.0
    hooks:
      - id: conventional-precommit-linter
        stages: [commit-msg]

  - repo: https://github.com/espressif/check-copyright/
    rev: v1.0.3
    hooks:
      - id: check-copyright
        args: ['--config', 'check_copyright_config.yaml']
